Logger
petrSchreiber/glfw-sandbox pull request #6
Opened 2021-06-28 01:19 UTC by milansky

Basic logger that takes a string argument, need to work out on other values and arguments.
This will suffice for now instead of writing cout for debugging.

2021-06-28 18:48 UTC, petrSchreiber requested changes
Milan, thanks a lot for bringing this important functionality to the engine - I have basically one and only suggestion regarding the wrapper signatures.

2021-06-28 18:48 UTC, petrSchreiber commented on src/glfw-sandbox/logger.cpp
> +void logger::trace(std::string text) {
In Nico's voice: "Are you sure the method changes internal state of the object?"

2021-06-28 18:48 UTC, petrSchreiber commented on src/glfw-sandbox/logger.cpp
> +void logger::trace(std::string text) {
In Nico's voice: "Are you sure the parameter gets changed inside the method?"

2021-06-28 18:48 UTC, petrSchreiber commented on src/glfw-sandbox/logger.cpp
> +void logger::trace(std::string text) {
In Nico's voice: "Are you sure it is necessary to perform copy?"

2021-06-29 00:01 UTC, milansky commented
Function changed, takes constant value and reference applied so its not copied :)

2021-06-29 08:16 UTC, petrSchreiber approved these changes
Thank you very much for taking the suggestions into consideration 👍

2021-06-29 08:24 UTC, merged